# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, 8.0
link_with 'XTouch-iOS', 'XTouch-iOSTests'

pod 'SIOSocket', :podspec => 'https://raw.githubusercontent.com/MegaBits/SIOSocket/master/SIOSocket.podspec'
