# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'SocketRocket', '0.3.1-beta2'

target 'XTouch-iOS' do

end

target 'XTouch-iOSTests' do

end

